import type { Metadata } from "next";
import "./globals.css";
import { DM_Sans, Outfit } from "next/font/google";
import Footer from "./Components/GlobalElements/footer";
import BottomCta from "./Components/GlobalElements/bottomcta";
// import GlobalForm from "./Components/GlobalForm/form";

export const metadata: Metadata = {
  title: "Return my Money Site",
  description: "Generated by create next app",
};

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
});

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dmSans.className} ${outfit.className} antialiased`}>
        {/* <GlobalForm /> */}
        {children}
      </body>

      <BottomCta />
      <Footer />
    </html>
  );
}
